server:
  port: 8081

spring:
  application:
    name: ms-mascotas
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:sanos_salvos_mascotas_db}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

clients:
  ms-coincidencias:
    url: ${MS_COINCIDENCIAS_URL:http://localhost:8083}
  ms-geo:
    url: ${MS_GEO_URL:http://localhost:8082}