apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-coincidencias
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-coincidencias
  template:
    metadata:
      labels:
        app: ms-coincidencias
    spec:
      containers:
      - name: ms-coincidencias
        image: ECR_REGISTRY_PLACEHOLDER/sanos-salvos-ms-coincidencias:IMAGE_TAG_PLACEHOLDER
        env:
        - name: DB_HOST
          value: mysql-coincidencias
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: root
        - name: MS_MASCOTAS_URL
          value: http://ms-mascotas:8081
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          value: "user"
        - name: RABBITMQ_PASSWORD
          value: "password"
        - name: MS_GEO_URL
          value: http://ms-geo:8082
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: ms-coincidencias
spec:
  selector:
    app: ms-coincidencias
  ports:
  - port: 8083
    targetPort: 8083
