apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-geo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-geo
  template:
    metadata:
      labels:
        app: ms-geo
    spec:
      containers:
      - name: ms-geo
        image: ECR_REGISTRY_PLACEHOLDER/sanos-salvos-ms-geo:IMAGE_TAG_PLACEHOLDER
        env:
        - name: MYSQL_HOST
          value: mysql-geo
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DB
          value: sanos_salvos_geo_db
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: root
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: ms-geo
spec:
  selector:
    app: ms-geo
  ports:
  - port: 8082
    targetPort: 8082
