apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-notificaciones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-notificaciones
  template:
    metadata:
      labels:
        app: ms-notificaciones
    spec:
      containers:
      - name: ms-notificaciones
        image: ECR_REGISTRY_PLACEHOLDER/sanos-salvos-ms-notificaciones:IMAGE_TAG_PLACEHOLDER
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          value: "mysql-notificaciones"
        - name: DB_NAME
          value: "sanos_salvos_notificaciones_db"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "root"
        - name: MS_MASCOTAS_URL
          value: "http://ms-mascotas:8081"
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          value: "user"
        - name: RABBITMQ_PASSWORD
          value: "password"
        - name: MAIL_USERNAME
          value: "MAIL_USERNAME_PLACEHOLDER"
        - name: MAIL_PASSWORD
          value: "MAIL_PASSWORD_PLACEHOLDER"
        ports:
        - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: ms-notificaciones
spec:
  selector:
    app: ms-notificaciones
  ports:
  - port: 8085
    targetPort: 8085
