server:
  port: 8083 # Puerto definido para evitar choques con Gateway (8080), Mascotas (8081) y Geo (8082)

spring:
  application:
    name: ms-coincidencias
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3308}/sanos_salvos_coincidencias_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

rabbitmq:
  queue:
    reportes: ${RABBITMQ_QUEUE_REPORTES:reportes_queue}

notificaciones:
  exchange:
    name: notificaciones_exchange
  routing:
    key: notificaciones_routing_key

# Configuración de URLs para OpenFeign (estos puertos se sacan de la arquitectura global)
app:
  feign:
    ms-mascotas:
      url: ${MS_MASCOTAS_URL:http://localhost:8081}
    ms-geo:
      url: ${MS_GEO_URL:http://localhost:8082}

# Configuración base de Resilience4j 
resilience4j:
  circuitbreaker:
    instances:
      coincidenciasCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5000ms
        failureRateThreshold: 50
